#!/bin/sh

get_version () {
	test -f version && cat version && return
	git describe --tags --match "v[0-9]*" --dirty 2>/dev/null | sed -e 's/-/+/' -e 's/^v//'
}

V=$(get_version)
test -z "$V" && V=$(cat .default-version)
NEW="GIT_VERSION = $V"

test -r GIT-VERSION-FILE && test "$NEW" = "$(cat GIT-VERSION-FILE)" && exit
echo "$NEW" | tee GIT-VERSION-FILE >&2
