name: CI

on: [push, pull_request]

env:
  DEVELOPER: 1

jobs:
  windows-build:
    name: win build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: git-for-windows/setup-git-for-windows-sdk@v1
    - name: build
      shell: bash
      env:
        HOME: ${{runner.workspace}}
        NO_PERL: 1
      run: make
  regular:
    name: linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: prepare
      run: |
        sudo apt-get -q update
        sudo apt-get -q -y install language-pack-is libsvn-perl apache2 \
          libssl-dev libcurl4-openssl-dev libexpat-dev \
          tcl tk gettext zlib1g-dev perl-modules liberror-perl libauthen-sasl-perl \
          libemail-valid-perl libio-socket-ssl-perl libnet-smtp-ssl-perl
    - name: build
      run: make
    - name: test
      env:
        GIT_PROVE_OPTS: "--timer --jobs 4"
        GIT_TEST_OPTS: "--verbose-log -x --github-workflow-markup --no-chain-lint --no-bin-wrappers"
      run: make -C t prove
